[package]
name = "gateway-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
pingora = { version = "0.3.0", features = ["proxy"] }
async-trait = "0.1.83"
clap = { version = "3.2.25", features = ["derive"] }
log = "0.4.22"
prometheus = "0.13.4"
env_logger = "0.11.5"
